name: Atualizar Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v6

      - name: Sincronizar com Hugging Face
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: SaraBCoutinho/fakejobs_detection_gen_ai_project
          repo_type: space
          space_sdk: docker
          hf_token: ${{ secrets.HF_TOKEN }}
